services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: social-networking/web
#    command: ./start
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      POSTGRES_PASSWORD: "${postgres_password}"
      POSTGRES_USER: "$postgres_user"
      POSTGRES_DB: "$postgres_db"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:14
    user: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "$postgres_password"
      POSTGRES_DB: "$postgres_db"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4:5.5
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: secret
#      PGADMIN_LISTEN_PORT: 80
#    ports:
#      - "8080:80"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
#  pgadmin-data:


