# Generated by Django 4.0 on 2023-04-02 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsthrough',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='core.socialnetworkusers'),
        ),
        migrations.AlterField(
            model_name='socialnetworkusers',
            name='friends',
            field=models.ManyToManyField(related_name='social_network', through='core.FriendsThrough', to='core.SocialNetworkUsers'),
        ),
    ]
