# Generated by Django 4.0 on 2023-04-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_socialnetworkusers_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworkusers',
            name='friends',
            field=models.ManyToManyField(related_name='social_network', through='core.FriendsThrough', to='core.SocialNetworkUsers'),
        ),
    ]
