# Generated by Django 4.0 on 2023-04-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_socialnetworkusers_friends'),
    ]

    operations = [
        # migrations.AddConstraint(
        #     model_name='friendsthrough',
        #     constraint=models.UniqueConstraint(fields=('social_network_user', 'friend', 'type'), name='unique_social_friend_relation'),
        # ),
        # migrations.AddConstraint(
        #     model_name='friendsthrough',
        #     constraint=models.CheckConstraint(check=models.Q(True), name='user_not_as_friend'),
        # ),
    ]
