# Generated by Django 4.0 on 2023-04-02 06:13

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_friendsthrough_unique_social_friend_relation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendsthrough',
            constraint=models.UniqueConstraint(fields=('social_network_user', 'friend', 'relationship_type'), name='unique_social_friend_relation'),
        ),
        migrations.AddConstraint(
            model_name='friendsthrough',
            constraint=models.CheckConstraint(check=models.Q(('social_network_user', django.db.models.expressions.F('friend')), _negated=True), name='user_not_as_friend'),
        ),
    ]
