# Generated by Django 4.0 on 2023-04-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_friendsthrough_unique_social_friend_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsthrough',
            name='relationship_type',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('RECEIVED', 'RECEIVED')], max_length=10),
        ),
        migrations.AlterField(
            model_name='friendsthrough',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=10),
        ),
    ]
